name: Build Windows Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
    
    - name: Install Chocolatey packages
      run: |
        choco install pkgconfiglite
        choco install gtk-runtime
        choco install mingw
    
    - name: Install additional dependencies
      run: |
        # ALSA equivalent (not typically needed on Windows, as it uses a different audio API)
        # Jack2 equivalent (ASIO might be an alternative, but requires different handling)
        
        # GLib, ATK, Pango, GTK3 (installed via gtk-runtime above)
        
        # libxkbcommon equivalent
        curl -L -o xkbcommon-x64.zip https://github.com/microsoft/windows-rs/raw/0.48.0/crates/libs/WindowsXaml_x64/xkbcommon.dll
        7z x xkbcommon-x64.zip -o"C:\Windows\System32"
        
        # libGL equivalent (OpenGL is typically available on Windows)
        
        # Wayland is Linux-specific, no direct Windows equivalent
        
        # X11 libraries are Linux-specific, Windows uses its own windowing system

    - name: Setup environment variables
      run: |
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-binary
        path: target/release/*.exe
